config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :carts do
    resources :orders, only: [:destroy]
    member do
      post :checkout
    end
  end

  resources :products do
    resources :pics, only: [:show, :create, :destroy]
    member do
      get :add_to_cart
    end
  end

  resources :categories, only: [:index, :new, :create,:show]
  resources :subscribers

  get "home/welcome"
  root 'home#welcome'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :orders
  has_many :products, through: :orders

  def total_price
    orders.map {|order| order.quantity * order.product.price}.sum
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
  end

  def show
    @cart = Cart.find(params[:id])
  end

  def checkout
    @cart = Cart.find(params[:id])
    #your secret key: remember to change this to your live secret key in production
    # See your keys here: https://dashboard.stripe.com/account/apikeys
    Stripe.api_key = "sk_test_UvGqljRHkzGCHeTQgG4wZBq1"

    # Token is created using Stripe.js or Checkout!
    # Get the payment token submitted by the form:
    token = params[:stripeToken]

    # Charge the user's card:
    charge = Stripe::Charge.create(
     :amount => (@cart.total_price * 100).to_i,
     :currency => "usd",
     :description => "Charge order #{@cart.id}",
     :source => token,
    )

    @cart.update(status: "completed")
    flash[:notice] = "Thank you for your purchase"
    session.delete(:cart_id)
    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:notice] = "Card declined"
    redirect_to @cart
  end
end

app/views/carts/_items.html.erb
<h1 class="cart-title">Cart</h1>
<div class="table-cart">
  <table class="table table-hovered">
    <thead>
      <tr>
        <th></th>
        <th>Quantity</th>
        <th>Price</th>
      <tr>
    </thead>
    <tbody>
        <% @cart.orders.each do |order| %>
        <tr>
           <td><%= link_to image_tag(order.product.image.url(:thumb)), product_path(order.product) %> <%= order.product.name %></td>
           <td></br></br></br><%= order.quantity %></td>
           <td></br></br></br><%= number_to_currency(order.product.price) %></td>
           <td></br></br></br><%= link_to "x", [order.cart, order], method: :delete, data: {confirm: 'Are you sure you want to remove this item from your cart?'} %></td>
         <% end %>
       </tr>
    </tbody>
  </table>
</div>

<div class="cart-checkout pull-right">
  <p><strong>Total:</strong> <%= number_to_currency(@cart.total_price) %></p>
  <%= form_tag checkout_cart_path(@cart) do %>
    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js"
    data-key="pk_test_5YfcwOLRWfzdZ4HHQSRhmmYr"
    data-amount=<%= @cart.total_price * 100 %>
    data-name="Shoppelyft"
    data-description="Item Order"
    data-locale="auto"
    data-panel-label="Checkout"
    data-billingAddress="true"
    data-shippingAddress="true"
    </script>
  <% end %>

  <form action="/your-server-side-code" method="POST">
    <script
      src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="pk_test_5YfcwOLRWfzdZ4HHQSRhmmYr"
      data-amount="999"
      data-name="Demo Site"
      data-description="Widget"
      data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
      data-locale="auto"
      shippingAddress="true"
      billingAddress="true"
    </script>
  </form>
</div>

app/views/carts/index.html.erb
<% if @cart.present? %>
  <%= render 'carts/items' %>
<% else %>
  </br><h1 class="container"> Your cart is empty</h1>
<% end %>

app/views/carts/show.html.erb
<div>
  <%= render 'carts/items' %>
</div>