config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :carts do
    resources :orders, only: [:destroy]
    member do
      post :checkout
    end
  end

  resources :products do
    resources :pics, only: [:show, :create, :destroy]
    member do
      get :add_to_cart
    end
  end

  resources :categories, only: [:index, :new, :create,:show]
  resources :subscribers

  get "home/welcome"
  root 'home#welcome'
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :pics, dependent: :destroy
  belongs_to :category

  has_attached_file :image, styles: { medium: "400x400", thumb: "200x200>", index: "350x300#", large: "700x700#"}, default_url: "/images/:style/logo.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  accepts_nested_attributes_for :pics, :reject_if => lambda { |t| t['pic'].nil? }

  # search method for development env use LIKE
  # for production use ILIKE
  def self.search(search)
     where("name ILIKE ?", "%#{search}%")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC")
    else
      @products = Product.all.order('created_at DESC')
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @categories = Category.all.map{|c| [c.name, c.id] }
  end

  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id]
    @categories = Category.all.map{|c| [c.name, c.id] }

    if @product.save
      flash[:notice] = "Product was added successfully."
      redirect_to @product
    else
      flash.now[:alert] = "Product failed to save"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all.map{|c| [c.name, c.id ] }
  end

  def update
    @product = Product.find(params[:id])
    @product.category_id = params[:category_id]

    if @product.update_attributes(product_params)
      flash[:notice] = "Product was updated successfully."
      redirect_to @product
    else
      flash.now[:alert] = "There was an error updating the product."
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])

    if @product.destroy
      flash[:notice] = "\"#{@product.name}\" was deleted successfully."
      redirect_to products_path
    else
      flash.now[:alert] = "There was an error deleting the product."
      render :show
    end
  end

  def add_to_cart
    if session[:cart_id].blank?
      cart = Cart.create(status: "pending")
      session[:cart_id] = cart.id
      flash[:notice] = "Item added to cart"
    else
      cart = Cart.find(session[:cart_id])
    end

    product = Product.find(params[:id])
    cart.orders.create(product_id: product.id, quantity: 1)
    flash[:notice] = "Item added to cart"
    redirect_to cart
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :description, :category_id, :image)
  end
  
end

app/helpers/products_helper.rb
module ProductsHelper
  def current_user_authorized?
    current_user && current_user.admin?
  end

end

app/views/products/_form.html.erb
<div class="container" style="margin-bottom: 400px;">
<h1>Add an item</h1>
  <%= form_for @product, html: { multipart: true } do |f| %>
    <div class="form-all form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: "Product Name", required: true  %>
    </div>

    <div class="form-all form-group">
      <%= f.label :price %>
      <%= f.text_field :price, class: 'form-control', placeholder: "Price", required: true %>
    </div>

    <div class="form-all form-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Item Description", required: true %>
    </div>

    <div class="form-all form-group">
      <%= f.label "Select a category for this item" %>
      <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category", required: true) %>
    </div>

    <div class=" form-all form-group">
      <%= f.label "Add a thumbnail" %>
      <%= f.file_field :image %>
    </div>

    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<div>
  <%= render partial: 'products/form' %>
</div>

app/views/products/index.html.erb
<div class="products-index">
  <h1 class="title">Browse all our products</h1>
  <div class="row">
    <% @products.each do |product| %>
      <div class="item-info col-md-4">
        <li class="img-tog"><%= link_to image_tag(product.image.url(:medium)), product%></li>
        <div class="item-cap">
          <p><%= link_to product.name, product %></p>
          <p><%= number_to_currency(product.price)%></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<svg xmlns="http://www.w3.org/2000/svg">
  <filter id="blur1">
    <feGaussianBlur stdDeviation="3"/>
  </filter>
</svg>

app/views/products/new.html.erb
<div>
  <%= render partial: 'products/form' %>
</div>

app/views/products/show.html.erb
<div class="container">
  <% if current_user_authorized? %>
    <%= link_to "Edit Item", edit_product_path, class: 'btn btn-primary'%>
    <%= link_to "Delete Item", @product, method: :delete, data: {confirm: 'Are you sure you want to delete this item?'}, class: "btn btn-danger" %>
    <%= render 'pics/form', pic: Pic.new, product: @product %></br>
  <% end %>
</div>

<div class="products-page">
  <section class="product-info">
    <div class="col-md-6 pull-left"><%= link_to (image_tag(@product.image.url(:large))), @product.image.url(:large), data: {lightbox: "eaxmple-set"} %></div>
    <div class="col-md-6 pull-right">
      <h1><%= @product.name %></h1>
      <h2><%= number_to_currency(@product.price) %></h2>
      <p>
        <strong>Product Details:</strong></br>
        <%= markdown(@product.description) %>
      </p>
      <div class="checkout-btn"><%= link_to "Add to Cart", add_to_cart_product_path(@product), class: 'btn btn-default' %></div>
    </div>
  </section>

  <section class="product-thumbnails">
    <% @product.pics.each do |pic| %>
      <div class="col-sm-3">
        <%= link_to (image_tag (pic.image.url(:album))), pic.image.url(:album), data: {lightbox: "eaxmple-set"} %>
        <% if current_user_authorized? %>
          <%= link_to "Delete", [pic.product, pic], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this image?'} %>
        <% end %>
      </div>
    <% end %>
  </section>
</div>