config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :carts do
    resources :orders, only: [:destroy]
    member do
      post :checkout
    end
  end

  resources :products do
    resources :pics, only: [:show, :create, :destroy]
    member do
      get :add_to_cart
    end
  end

  resources :categories, only: [:index, :new, :create,:show]
  resources :subscribers

  get "home/welcome"
  root 'home#welcome'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :orders
  has_many :products, through: :orders

  def total_price
    orders.map {|order| order.quantity * order.product.price}.sum
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, dependent: :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
end

app/models/pic.rb
class Pic < ActiveRecord::Base
  belongs_to :product
  has_attached_file :image, styles: { medium: "200x200", thumb: "300x300", album: "600x600", big: "1000x1000"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :pics, dependent: :destroy
  belongs_to :category

  has_attached_file :image, styles: { medium: "400x400", thumb: "200x200>", index: "350x300#", large: "700x700#"}, default_url: "/images/:style/logo.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  accepts_nested_attributes_for :pics, :reject_if => lambda { |t| t['pic'].nil? }

  # search method for development env use LIKE
  # for production use ILIKE
  def self.search(search)
     where("name ILIKE ?", "%#{search}%")
  end
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  validates :name, :email, :source, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum role: [:standard, :premium, :admin]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
  end

  def show
    @cart = Cart.find(params[:id])
  end

  def checkout
    @cart = Cart.find(params[:id])
    #your secret key: remember to change this to your live secret key in production
    # See your keys here: https://dashboard.stripe.com/account/apikeys
    Stripe.api_key = "sk_test_UvGqljRHkzGCHeTQgG4wZBq1"

    # Token is created using Stripe.js or Checkout!
    # Get the payment token submitted by the form:
    token = params[:stripeToken]

    # Charge the user's card:
    charge = Stripe::Charge.create(
     :amount => (@cart.total_price * 100).to_i,
     :currency => "usd",
     :description => "Charge order #{@cart.id}",
     :source => token,
    )

    @cart.update(status: "completed")
    flash[:notice] = "Thank you for your purchase"
    session.delete(:cart_id)
    redirect_to root_path

  rescue Stripe::CardError => e
    flash[:notice] = "Card declined"
    redirect_to @cart
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def welcome
    @products = Product.all
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def destroy
    @cart = Cart.find(params[:cart_id])
    @order = @cart.orders.find(params[:id])

    if @order.destroy
      flash[:notice] = "Item removed from your cart."
      redirect_to @cart
    else
      flash[:alert] = "There was a problem removing the item."
      redirect_to @cart
    end
  end
  
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :require_sign_in, except: [:index, :show]

  before_action :authorize_user, only: [:destroy]

  def show
    @product = Product.find(params[:id])
    @pic = @product.pics.all
  end

 def create
   @product = Product.find(params[:product_id])
   @pic = @product.pics.new(pic_params)

   if @pic.save
     flash[:notice] = "Image saved successfully."
     redirect_to [@product]
   else
     flash[:alert] = "Image failed to save."
     redirect_to [@product]
   end
 end

 def destroy
  @product = Product.find(params[:product_id])
  @pic = @product.pics.find(params[:id])

  if @pic.destroy
    flash[:notice] = "Image was deleted successfully."
    redirect_to @product
  else
    flash[:alert] = "Image couldn't be deleted. Try again."
    redirect_to @product
  end
end

private

 def pic_params
   params.require(:pic).permit(:image)
 end

  def authorize_user
    pic = Pic.find(params[:id])
    unless current_user.admin?
      flash[:alert] = "You do not have permission to delete this image"
      redirect_to [pic.product]
    end
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC")
    else
      @products = Product.all.order('created_at DESC')
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @categories = Category.all.map{|c| [c.name, c.id] }
  end

  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id]
    @categories = Category.all.map{|c| [c.name, c.id] }

    if @product.save
      flash[:notice] = "Product was added successfully."
      redirect_to @product
    else
      flash.now[:alert] = "Product failed to save"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all.map{|c| [c.name, c.id ] }
  end

  def update
    @product = Product.find(params[:id])
    @product.category_id = params[:category_id]

    if @product.update_attributes(product_params)
      flash[:notice] = "Product was updated successfully."
      redirect_to @product
    else
      flash.now[:alert] = "There was an error updating the product."
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])

    if @product.destroy
      flash[:notice] = "\"#{@product.name}\" was deleted successfully."
      redirect_to products_path
    else
      flash.now[:alert] = "There was an error deleting the product."
      render :show
    end
  end

  def add_to_cart
    if session[:cart_id].blank?
      cart = Cart.create(status: "pending")
      session[:cart_id] = cart.id
      flash[:notice] = "Item added to cart"
    else
      cart = Cart.find(session[:cart_id])
    end

    product = Product.find(params[:id])
    cart.orders.create(product_id: product.id, quantity: 1)
    flash[:notice] = "Item added to cart"
    redirect_to cart
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :description, :category_id, :image)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :require_sign_in

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:notice] = "Profile was updated successfully."
      redirect_to @user
    else
      flash.now[:alert] = "There was an error updating your profile. Please try again."
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :role)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
   options = {
     filter_html:     true,
     hard_wrap:       true,
     space_after_headers: true
   }

   extensions = {
     autolink:           true,
     superscript:        true,
     disable_indented_code_blocks: true
   }

   renderer = Redcarpet::Render::HTML.new(options)
   markdown = Redcarpet::Markdown.new(renderer, extensions)
   markdown.render(text).html_safe
  end

  def category
    @categories = Category.all
  end

  def subscriber
    @subscriber = Subscriber.new
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def current_user_authorized?
    current_user && current_user.admin?
  end

end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <ul class="col-md-4" id="social-links">
        <h4>Follow Us</h4>
        <li><a href="#"><i class="fa fa-facebook-official" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
      </ul>

      <ul class="col-md-4">
        <h4>About Adroit</h4>
        <li><%= link_to "FAQ", "#" %></li>
        <li><%= link_to "Support", "#" %></li>
        <li><%= link_to "Privacy Policy", "#" %></li>
        <li><%= link_to "Terms & Conditions", "#" %></li>
        <li><%= link_to "Contact", "#" %></li>
      </ul>
      
      <ul class="col-md-4">
        <% if cookies[:saved_subscriber] %>
          Thank you for subscribing!
        <% else %>
          <h4>Subscribe to our newsletter</h4>
          <li><%= render 'subscribers/form' %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="copyright container">
    <p>Copyright <i class="fa fa-copyright" aria-hidden="true"></i> 2017 Adroit</p>
  <div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar-top <%= yield(:nav_style) %>">
  <li><%= link_to image_tag("logo.png"), root_path %></li>

  <div id="nav-links">
    <li class="box"><%= link_to "Home", root_path %></li>
    <li class="box"><%= link_to "Browse", products_path %></li>
    <% category.each do |category| %>
      <li class="box"><%= link_to category.name, category %></li>
    <% end %>
  </div>

  <% if current_user_authorized? %>
    <li><%= link_to "Add Item", new_product_path %></li>
  <% end %>

  <% if current_user.present? %>
    <li class="pull-right"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
  <% end %>
  <div>
    <% if @cart.present? %>
      <li class="cart-btn pull-right"><i class="fa fa-shopping-cart"></i><%= link_to "Cart", cart_path(@cart)%><span class="badge"><%=@cart.products.count%></span></li>
    <% else %>
      <li class="cart-btn pull-right"><i class="fa fa-shopping-cart"></i><%= link_to "Cart", carts_path %></li>
    <% end %>

    <li class="pull-right" id="social-btn"><a href="#"><i class="fa fa-facebook"></i></a></li>
    <li class="pull-right" id="social-btn"><a href="#"><i class="fa fa-instagram"></i></a></li>
    <li class="pull-right" id="social-btn"><a href="#"><i class="fa fa-twitter"></i></a></li>
    <li class="search-bar pull-right">
       <%= form_tag(products_path, :method => "get", id: "search-form") do %>
         <%= text_field_tag :search, params[:search], placeholder: "Search" %>
           <%= button_tag(type: "submit", class: "btn") do %>
            <i class="fa fa-search"></i>
         <% end %>
       <% end %>
    </li>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Adroit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Catamaran" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <% if flash[:notice] %>
    <div class="alert-wrapper">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert-wrapper">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert-wrapper">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

  <%= render 'layouts/footer' %>
<%= yield %>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>